### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
trust_remote_code: true

video_fps: 2.0
video_maxlen: 10
video_max_pixels: 691200 # 960*720
use_audio_in_video: False

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: None  # set in cmd args
template: qwen2_vl
cutoff_len: 8192
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/vs2_qwen2_5vl_sft_17k_5e-5_2fps_960_720_8192
logging_steps: 5
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
export_hub_model_id: videoscore2/vs2_qwen2_5vl_sft_17k_5e-5_2fps_960_720_8192
hf_hub_token: null

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
